spring:
  profiles:
    active: dev-postgres
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: false
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:pw26s-dev
---
spring:
  config:
    activate:
      on-profile: dev-postgres
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/contas
    username: postgres
    password: 01thiago
  jpa:
    hibernate:
      ddl-auto: create-drop