spring:
  profiles:
    active: dev-postgres
  datasource:
    url: "jdbc:postgresql://ep-young-breeze-a48uaknj-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"
    username: "default"
    password: "hcWRi0unLd1j"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create # cria as tabelas automaticamente
    show-sql: true # habilita o log das queries no console